### PR TITLE
Display gravatar by default

### PR DESCRIPTION
**Pull request by bmb330**
For issue #24

### CODE REVIEW

**Comment by bmb330** [comment]
Anyone like to review this, or can I merge? Any input would be appreciated.

**Comment by rhuberdeau** [comment]
What made you change "unless" to "if not"? I don't have the code base open in front of me, but whichever we're using in other places we should use here. We want to keep the same code style throughout the application.

  Also, I don't think we should put the user's email address in the gravatar url. This is personal information that we would be exposing to anyone who took the time to inspect the image. The username would probably be more appropriate.

**Comment by bmb330** [comment]
Sorry, I am pretty new to Ruby and Rails and was under the impression I needed to use if not as the unless can not have elsif following it. If I am confused please let me know as I do want to follow the proper way.

As for the gravatar url, it is generated from the Digest::MD5.hexdigest by passing in the user's email, but it is sent to the client as a hash and will not include the actual email address of the user.

Thanks for looking over the code.

**Comment by rhuberdeau** [comment]
No problem man-that's what these discussions are for.

I had a chance to give this another look and I think things can be simplified. If we focus on the path that returns the user's avatar first, then the code ends up something like:
    
    def author_avatar(post)
      if post.author.avatar.present? && !post.anonymous?
        image_tag post.author.avatar.thumb.url, size: '18', alt: post.author.username
      else
        gravatar stuff
      end
    end

This is a lot easier to follow and to test for.

Also, and I could be alone in this opinion, but I'm not sure why we need to make a call to Gravatar for each person that doesn't have an avatar. Why not just download the default image into the application, or make the same exact call for everyone and cache the response? This will cut down on external calls  and therefor won't impact page load time as much.

**Comment by bmb330** [comment]
Changed author_avatar, based on your suggestion. Kept the elsif for the case of anonymous posts.

As for the Gravatar, I think it would be better to use the external call, due to users changing their Gravatar image. Also, if I am not mistaking, if other applications use Gravatar images the image would be cached locally in the client browser, requiring fewer requests in general. At least that is how I understood it. Let me know what you think.

**Comment by rhuberdeau** [comment]
I'm not too familiar with Gravatar and how it works exactly so I can't really say. Anyone else have an opinion?

**Comment by bmb330** [comment]
Anyone have any other comments on this or can we merge this? If no one disapproves, I can just go ahead and merge it. Thanks.

**Pull request merged**
