### PR TITLE
use Javascript to display relative dates

### PR DESCRIPTION
**Pull request by samnang**
See #18 

http://timeago.yarp.com/

### CODE REVIEW

**Comment by samnang** [comment]
@NARKOZ which way do you decide to use to include javascript third parties in the project? Gemify asset version of the library or something else like https://rails-assets.org/? For now, I put raw file under vendor, but happy to discuss which way you have in mind.

**Comment by NARKOZ** [comment]
Let's use gemified assets and rails-assets.org where possible. Easier to maintain and update. 
Here I would use `rails-timeago` gem, as it looks up to date and provides additional helpers.

**Comment by samnang** [comment]
@NARKOZ please take a look, I've switched to use rails-timeago instead.

**Comment by NARKOZ** [comment]
Thank you.

**Pull request merged**
